/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export { };

declare global {
  // @ts-ignore
  export * as z from 'zod';
  // @ts-ignore
  import('zod');
}
